// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminNav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar navbar-light\"><div class=\"container-fluid justify-between\"><i class=\"bi bi-shield-lock navbar-icon\"></i><div class=\"d-flex justify-content-end position-relative\"><a class=\"nav-link\" href=\"/admin/selectSupplyManufacturer\">Supply<br>Product</a> <a class=\"nav-link\" href=\"/admin/selectWithdrawManufacturer\">Withdraw <br>Product</a><div class=\"nav-link\" onclick=\"toggleSubmenu(&#39;submenu-manufacturers&#39;)\">Manage<br>Manufacturers<div class=\"submenu\" id=\"submenu-manufacturers\"><a href=\"/admin/addManufacturer\">Add</a> <a href=\"/admin/renameManufacturer\">Rename</a> <a href=\"/admin/removeManufacturer\">Remove</a></div></div><div class=\"nav-link\" onclick=\"toggleSubmenu(&#39;submenu-storages&#39;)\">Manage<br>Storages<div class=\"submenu\" id=\"submenu-storages\"><a href=\"/admin/addStorage\">Add</a> <a href=\"/admin/renameStorage\">Rename</a> <a href=\"/admin/removeStorage\">Remove</a></div></div><div class=\"nav-link\" onclick=\"toggleSubmenu(&#39;submenu-products&#39;)\">Manage<br>Products<div class=\"submenu\" id=\"submenu-products\"><a href=\"/admin/searchProducts\">Search</a> <a href=\"/admin/productHistory\">History</a></div></div><div class=\"nav-link\" onclick=\"toggleSubmenu(&#39;submenu-users&#39;)\">Manage<br>Users<div class=\"submenu\" id=\"submenu-users\"><a href=\"/admin/addUser\">Add</a> <a href=\"/admin/changePassword\">Change Password</a> <a href=\"/admin/disableUser\">Disable</a> <a href=\"/admin/enableUser\">Enable</a></div></div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
