name: Build Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'backend/**'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Build dokcer image
        uses: ./.github/workflows/reusable-build.yml
        with:
          tag: ${{ env.NEW_VERSION }}
          push: false
