name: Deployment Workflow

on:
  push:
    branches:
      - main
      - feautre/us-e13-deployment
    # paths:
    #   - 'Dockerfile'
    #   - 'backend/**'

env:
  VM_HOST: "141.147.38.161"
  VM_USER: "ubuntu"
  VM_SSH_KEY: ${{ secrets.PRIVATE_KEY }}
  PROJECT_PATH: "/home/ubuntu/swi/SWIProjekt"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment_version.outputs.NEW_VERSION }}

    steps:
      - name: Creating deploy_key
        run: |
          echo "Creating deploy key"
          echo "${VM_SSH_KEY}" >> deploy_key
          echo "chmod deploy_key"
          chmod 400 deploy_key

      - name: Deploy to VM
        run: |
          ssh -i deploy_key $VM_USER@$VM_HOST << EOF
            ls -l ${PROJECT_PATH}
          EOF