name: Deployment Workflow

on:
  push:
    branches:
      - main
      - feautre/us-e13-deployment
    # paths:
    #   - 'Dockerfile'
    #   - 'backend/**'

jobs:
  deploy:
    name: Tag a new release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment_version.outputs.NEW_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            swiproject:${{ github.sha }}
      
      - name: Deploy to VM
        env:
          VM_HOST: "141.147.38.161"
          VM_USER: "ubuntu"
          VM_SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT_PATH: "/home/ubuntu/swi/SWIProjekt"
        run: |
          echo "${VM_SSH_KEY}" >> deploy_key
          chmod 400 deploy_key

          ssh -i deploy_key $VM_USER@$VM_HOST << EOF
            ls -l ${PROJECT_PATH}
          EOF