on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        type: string
      push:
        description: 'Whether to push the Docker image to the registry'
        required: true
        type: boolean

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/boushiseikatsu/swiprojekt:latest
            ghcr.io/boushiseikatsu/swiprojekt:${{ inputs.tag }}
