name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Run Tests
        working-directory: ./backend
        run: go test ./... -v -coverprofile=coverage.out

      - name: Print Coverage
        working-directory: ./backend
        run: go tool cover -func=coverage.out
